import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner/index.js'
import Navbar from '@/components/navbar'
import Card from '@/components/card/card'

const roboto = Roboto({ subsets: ['latin'], weight: "400",weight:"700" })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={roboto.className}>
        <Navbar username="sanjar@gmail.com"/>
        <Banner 
          title="Clifford the red dog" 
          subTitle="a very cute dog" 
          imgUrl="/static/clifford.webp" 
        />
        <Card imgUrl="/static/clifford.webp" size="large" />
        <Card imgUrl="/static/clifford.webp" size="medium" />
        <Card imgUrl="/static/clifford.webp" size="small" />
      </main>
    </>
  )
}
